export enum PaymentOrderState {
    PAYMENT_ORDER_ACTIVE = "PAYMENT_ORDER_ACTIVE",
    PAYMENT_ORDER_BILLED = "PAYMENT_ORDER_BILLED",
    PAYMENT_ORDER_PENDING_CONFIRMATION = "PAYMENT_ORDER_PENDING_CONFIRMATION",
    PAYMENT_ORDER_REJECTED = "PAYMENT_ORDER_REJECTED",
    PAYMENT_ORDER_REFUNDED = "PAYMENT_ORDER_REFUNDED",
    PAYMENT_ORDER_PARTIALLY_REFUNDED = "PAYMENT_ORDER_PARTIALLY_REFUNDED",
}
